`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 06/20/2026 03:25:21 PM
// Design Name: 
// Module Name: image_filter_top_tb
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module image_filter_top_tb;

    // Input image dimensions
    parameter W_IN = 512;
    parameter H_IN = 512;
    parameter KERNEL = 4; // 0 = IDENTITY, 1 = Gauss Blur, 2 = Sobel X, 3 = Sobel (full), 4 = Sharp, 5 = Scharr
    parameter NO_OF_CHANNELS = 3; // 1 = Grayscale, 3 = RGB
    parameter DATA_WIDTH = (NO_OF_CHANNELS<<3);
    parameter CLK_PERIOD = 10;

    reg aclk;
    reg aresetn;

    // AXI Slave Interface
    reg  [DATA_WIDTH-1:0] s_axis_tdata;
    reg                   s_axis_tvalid;
    wire                  s_axis_tready;
    reg                   s_axis_tlast;

    // AXI Master Interface
    wire [DATA_WIDTH-1:0] m_axis_tdata;
    wire                  m_axis_tvalid;
    reg                   m_axis_tready;
    wire                  m_axis_tlast;

    image_filter_top #(
        .W_IN(W_IN),
        .H_IN(H_IN),
        .KERNEL(KERNEL),
        .NO_OF_CHANNELS(NO_OF_CHANNELS)
    ) UUT (
        .clk(aclk),
        .reset_n(aresetn),
        .s_axis_tdata(s_axis_tdata),
        .s_axis_tvalid(s_axis_tvalid),
        .s_axis_tready(s_axis_tready),
        .s_axis_tlast(s_axis_tlast),
        .m_axis_tdata(m_axis_tdata),
        .m_axis_tvalid(m_axis_tvalid),
        .m_axis_tready(m_axis_tready),
        .m_axis_tlast(m_axis_tlast)
    );

    always #(CLK_PERIOD/2) aclk = ~aclk;

    // Memory array to hold the image
    reg [DATA_WIDTH-1:0] image_ram [0:(W_IN*H_IN)-1];
    integer fd_out;

    
    initial begin
        m_axis_tready <= 1; // always ready
    end

    // injecting the image
    integer i, j;
    integer pixel_idx = 0;

    initial begin
        aclk = 0;
        aresetn = 0;
        s_axis_tvalid = 0;
        s_axis_tdata = 0;
        s_axis_tlast = 0;

        // loading the hex file generated by python

        //$readmemh("C:/Users/jaish/OneDrive/Documents/FPGA/image_filter_IP/python_image_tools/input_image.hex", image_ram); // for grayscale
        $readmemh("C:/Users/jaish/OneDrive/Documents/FPGA/image_filter_IP/python_image_tools/input_image_rgb.hex", image_ram); // for RGB
        #100;
        aresetn = 1;
        #20;

        $display("Streaming Image...");

        for (i = 0; i < H_IN; i = i + 1) begin
            for (j = 0; j < W_IN; j = j + 1) begin
                s_axis_tvalid <= 1;
                s_axis_tdata  <= image_ram[pixel_idx];
                s_axis_tlast  <= (j == W_IN - 1) ? 1'b1 : 1'b0;

                @(posedge aclk);
                while (s_axis_tready !== 1'b1) begin
                    @(posedge aclk);
                end
                pixel_idx = pixel_idx + 1;
            end
        end

        // flush padding
        $display("Image sent. Flushing pipeline...");
        for (j = 0; j < W_IN+15; j = j + 1) begin
            s_axis_tvalid <= 1;
            s_axis_tdata  <= 8'h00; 
            s_axis_tlast  <= (j == W_IN - 1) ? 1'b1 : 1'b0; 

            @(posedge aclk);
            while (s_axis_tready !== 1'b1) begin
                @(posedge aclk);
            end
        end

        s_axis_tvalid <= 0;
        s_axis_tlast  <= 0;
    end

    // for output file
    integer out_pixel_count = 0;
    
    initial begin
        // opening file to write outputs
        //fd_out = $fopen("C:/Users/jaish/OneDrive/Documents/FPGA/image_filter_IP/python_image_tools/output_image.hex", "w"); // for grayscale
        fd_out = $fopen("C:/Users/jaish/OneDrive/Documents/FPGA/image_filter_IP/python_image_tools/output_image_rgb.hex", "w"); // for RGB

    end

    always @(posedge aclk) begin
        if (m_axis_tvalid && m_axis_tready) begin
            // writing hex string to file
            // $fdisplay(fd_out, "%02x", m_axis_tdata); // for grayscale
            $fdisplay(fd_out, "%06x", m_axis_tdata); // for RGB
            out_pixel_count = out_pixel_count + 1;
            
            // closing file and stop simulation when all pixels arrive
            if (out_pixel_count == (W_IN * H_IN)) begin
                $display("SUCCESS: Captured %0d pixels.", out_pixel_count);
                $fclose(fd_out);
                #(CLK_PERIOD * 10);
                $finish;
            end
        end
    end

endmodule